<a href="https://colab.research.google.com/github/Suraj945gh/Python-LabCodes/blob/main/Assignment_2_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***Question 1***

In [ ]:
mylist = [12,34,'Suraj', True, 34.45,'Kush']

import random
print(random.choice(mylist))

34


**Question 2**

In [ ]:
list1 = [12,34,56,123,('Static','Dynamic'),False,78]  # a list containing tuple
count = 0
for item in list1:
  if type(item) is tuple:
    break
  else:
    count +=1

print("The final count until tuple is encountered: ",count)

The final count until tuple is encountered:  4


**Question 3**

In [ ]:
# Dictionary:

country_curr = {'India':'Rupees', 'USA':'Dollar', 'UK':'Pound', 'Japan':'Yen', 'Dubai':'Dirham'}
print(country_curr)

{'India': 'Rupees', 'USA': 'Dollar', 'UK': 'Pound', 'Japan': 'Yen', 'Dubai': 'Dirham'}


**Question 4**

In [ ]:
my_tuple = ('Suraj','Antariksh','IRC',2024,True,19)

#total_length = len(my_tuple)
#print(total_length)

print(my_tuple[::-1])
#print(my_tuple[1:5])

(19, True, 2024, 'IRC', 'Antariksh', 'Suraj')


Numpy in Python is a general-purpose array-processing package. It provides a high-performance multidimensional array object and tools for working with these arrays. It is the fundamental package for scientific computing with Python

**Question 5**

In [ ]:
import numpy as np

myarr = np.ones(6,dtype='int')
print(myarr)

[1 1 1 1 1 1]


**Question 6**

In [ ]:
numpy_arr = [[1,2,3],[4,5,6],[7,8,9]]
specified_row = [1,2,3]

if specified_row in numpy_arr:
  print("Specified row is present")
else:
  print("Specified row is not present")

Specified row is present


**Question 7**

In [ ]:
arr1 = np.array([[3,4,5], [2,2,3], [1,1,8]])
arr2 = np.array([[5,6,7], [1,0,0], [2,6,2]])
mul = arr1*arr2
div = arr2/arr1
print("Multiplication: \n",mul)
print("Division: \n",div)

Multiplication: 
 [[15 24 35]
 [ 2  0  0]
 [ 2  6 16]]
Division: 
 [[1.66666667 1.5        1.4       ]
 [0.5        0.         0.        ]
 [2.         6.         0.25      ]]


**Question 8**

In [ ]:
my_arr = np.array([1,2,3,4,1,1,34,6,7,4,3,3,3,1,2,1,2])

freq_value = np.bincount(my_arr).argmax()
print("The most frequent value is: ", freq_value)

# Calculating minimum and maximum using argmin and argmax methods
print("Minimum element= ",my_arr[my_arr.argmin()])
print("Maximum element= ",my_arr[my_arr.argmax()])

The most frequent value is:  1
Minimum element=  1
Maximum element=  34


**Question 9**

In [ ]:
import numpy as np

ini_arr = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])

# printing initial arrays
print("initial array \n", str(ini_arr))

# Multiplying arrays
result = ini_arr.flatten()

# printing result
print("New resulting array: \n", result)

initial array 
 [[1 2 3]
 [2 4 5]
 [1 2 3]]
New resulting array: 
 [1 2 3 2 4 5 1 2 3]


***Question 10***

In [ ]:
multi_arr = np.array([[3,4,1],[1,5,1],[5,8,9]])

print(multi_arr)
newarr = multi_arr.sum(axis=0)
print(newarr)
print(multi_arr.dtype)

[[3 4 1]
 [1 5 1]
 [5 8 9]]
[ 9 17 11]
int64


***Question 11***

In [ ]:
array_values = [2,3,3,4,4,5,71,12,9]

print("The average of the values is ", np.average(array_values))
print("The variance of the values is ", np.var(array_values))
print("The standard deviation of the values is ",np.std(array_values))

The average of the values is  12.555555555555555
The variance of the values is  436.2469135802469
The standard deviation of the values is  20.88652468890521


***Question 12***

The ***char.join()*** function in Python’s NumPy library is used to concatenate an array of strings in a given sequence seq. It basically **returns a string.**

In [ ]:
strarray = np.array(['Hello','World','Python','Here'])
print("Before adding space:",strarray)

newarray = np.char.join(' ', strarray)
print("After adding space:", newarray)
print(strarray.dtype)
print(newarray.dtype)

# newarray= np.char.join(separray, myarray)
# Here separray is separator array i.e. here ' ' and myarray is the array that we wanna change


Before adding space: ['Hello' 'World' 'Python' 'Here']
After adding space: ['H e l l o' 'W o r l d' 'P y t h o n' 'H e r e']
<U6
<U11


***Question 13***

In [ ]:
arri= np.array([[3,4,1],[1,5,1],[5,8,9]])
print("Unsorted array:\n",arri)
print("Sorted array:\n")
np.sort(arri)

Unsorted array:
 [[3 4 1]
 [1 5 1]
 [5 8 9]]
Sorted array:



array([[1, 3, 4],
       [1, 1, 5],
       [5, 8, 9]])